$(document).ready(function(){

  $(".wow1").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow1").mouseenter(function(){
    $(".wow11").css("z-index","8");
  });
  $(".wow2").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow2").mouseenter(function(){
    $(".wow22").css("z-index","8");
  });
  $(".wow3").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow3").mouseenter(function(){
    $(".wow33").css("z-index","8");
  });
  $(".wow4").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow4").mouseenter(function(){
    $(".wow44").css("z-index","8");
  });
  $(".wow5").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow5").mouseenter(function(){
    $(".wow55").css("z-index","8");
  });
  $(".wow6").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow6").mouseenter(function(){
    $(".wow66").css("z-index","8");
  });
  $(".wow7").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow7").mouseenter(function(){
    $(".wow77").css("z-index","8");
  });
  $(".wow8").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow8").mouseenter(function(){
    $(".wow88").css("z-index","8");
  });
  $(".wow9").mouseenter(function(){
    $(this).css("z-index","8");
  });
  $(".wow9").mouseenter(function(){
    $(".wow99").css("z-index","8");
  });
  
  
 $(".wow11").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow22").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow33").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow44").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow55").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow66").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow77").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow88").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  $(".wow99").mouseleave(function(){
    $(this).css("z-index","-1");
  });
  });
